name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: any
  meta: any
  json_annotation: any
  cached_network_image: any
  flutter_rating_bar: any
  provider: any
  async: any
  rxdart: any

  untitled:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: any
  build_runner: any
  json_serializable: any
  fake_async: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: PTSans
      fonts:
        - asset: assets/font/PTSans-Regular.ttf
          weight: 400
        - asset: assets/font/PTSans-Bold.ttf
          weight: 700
    - family: NavigationBarIcons
      fonts:
        - asset: assets/icon/navigation_bar_icons.ttf
    - family: ProfileIcons
      fonts:
        - asset: assets/icon/profile_icons.ttf
