name: untitled
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: any
  async: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  fake_async: ^1.3.1
  mocktail: ^1.0.2
